text_files_to_ignore = ['bagit.txt', 'metadata.json', 'bagit.txt', 'bag-info.txt', 'manifest-sha256.txt', 'tagmanifest-sha256.txt']
image_extensions = ['.jpg', '.jpeg', '.tif', '.tiff', '.png', '.gif', '.bmp']
video_extensions = ['.mp4', '.avi', '.mov', '.flv', '.mkv']
audio_extensions = ['.wav', '.mp3', '.aac', '.m4a', '.flac', '.ogg', '.aif', '.aiff']
text_extensions = ['.txt', '.doc', '.docx', '.rtf', '.odt']